# Generated by Django 4.2.8 on 2024-01-02 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptInviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('token', models.CharField(db_index=True, editable=False, max_length=256)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='users.thingbookergroup')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'token')},
            },
        ),
    ]
