# Generated by Django 4.2.8 on 2024-01-14 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thingbooker.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_acceptinvitetoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='thingbookeruser',
            managers=[
                ('objects', thingbooker.users.models.ThingbookerUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='acceptinvitetoken',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='users.thingbookergroup'),
        ),
        migrations.AlterField(
            model_name='acceptinvitetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
