# Generated by Django 4.2.8 on 2023-12-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_thingbookergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingbookeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='thingbookeruser',
            name='username',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
