# Generated by Django 4.2.8 on 2023-12-24 15:40

import django.core.validators
from django.db import migrations, models
import thingbooker.users.models
import thingbooker.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_thingbookeruser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingbookeruser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=thingbooker.users.models.user_avatar_path, validators=[django.core.validators.validate_image_file_extension, thingbooker.users.validators.validate_image_is_square]),
        ),
    ]
