# Generated by Django 4.2.8 on 2024-03-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_booking_end_date_alter_booking_num_people_and_more'),
        ('users', '0003_alter_thingbookeruser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptThingInviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('token', models.CharField(db_index=True, editable=False, max_length=256)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='things.thing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'token')},
            },
        ),
    ]
