# Generated by Django 4.2.8 on 2024-03-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_acceptthinginvitetoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptInviteToken',
            new_name='AcceptGroupInviteToken',
        ),
    ]
