# Generated by Django 4.2.8 on 2023-12-30 12:23

import django.core.validators
from django.db import migrations, models
import thingbooker.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_thingbookeruser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingbookergroup',
            name='group_picture',
            field=models.ImageField(null=True, upload_to=thingbooker.users.models.group_picture_path),
        ),
        migrations.AlterField(
            model_name='thingbookeruser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=thingbooker.users.models.user_avatar_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
