# Generated by Django 4.2.8 on 2024-03-26 17:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, "Can't make a booking with 0 or less persons")], verbose_name='Number of guests using the thing'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.TextField(blank=True, choices=[('declined', 'Booking is declined'), ('accepted', 'Booking is accepted'), ('waiting', 'Booking is waiting for approval')], default='waiting', max_length=10),
        ),
    ]
